// (C) 2016 Masato Kokubo
plugins {
    id 'java-library'
    id 'groovy'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly        'log4j:log4j:1.+'
    testRuntimeOnly    'log4j:log4j:1.+'
    compileOnly        'org.apache.logging.log4j:log4j-api:2.+'
    testRuntimeOnly    'org.apache.logging.log4j:log4j-core:2.+'

    compileOnly        'org.slf4j:slf4j-api:1.7.+'
    testRuntimeOnly    'ch.qos.logback:logback-classic:1.2.+'

    compileOnly        'com.mchange:c3p0:0.+'
    testRuntimeOnly    'com.mchange:c3p0:0.+'
    compileOnly        'com.zaxxer:HikariCP:7.0.+'
    testRuntimeOnly    'com.zaxxer:HikariCP:7.0.+'
    compileOnly        'org.apache.commons:commons-dbcp2:2.+'
    testRuntimeOnly    'org.apache.commons:commons-dbcp2:2.+'
//  compileOnly        'org.apache.tomcat:tomcat-jdbc:10.0.+'
//  testRuntimeOnly    'org.apache.tomcat:tomcat-jdbc:10.0.+'
    compileOnly        'org.apache.tomcat:tomcat-jdbc:11.0.+'
    testRuntimeOnly    'org.apache.tomcat:tomcat-jdbc:11.0.+'
//  compileOnly        'org.apache.tomcat:tomcat-jdbc:10.1.+'
//  testRuntimeOnly    'org.apache.tomcat:tomcat-jdbc:10.1.+' // Error in DataSourceFactory.createDataSource(jdbcProperties).

    testRuntimeOnly    'com.ibm.db2.jcc:db2jcc:db2jcc4'
    testRuntimeOnly    'org.mariadb.jdbc:mariadb-java-client:2.+'
//  testRuntimeOnly    'org.mariadb.jdbc:mariadb-java-client:3.+' // The acquisition of byte array becomes a character string
    testRuntimeOnly    'com.mysql:mysql-connector-j:8.4.+'
    compileOnly        'com.oracle.database.jdbc:ojdbc8:19.+'
    testRuntimeOnly    'com.oracle.database.jdbc:ojdbc8:19.+'
    testRuntimeOnly    'org.postgresql:postgresql:42.+'
    testRuntimeOnly    'org.xerial:sqlite-jdbc:3.+'
    compileOnly        'com.microsoft.sqlserver:mssql-jdbc:13.2.1.jre11'
    testRuntimeOnly    'com.microsoft.sqlserver:mssql-jdbc:13.2.1.jre11'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.+'
    testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine:5.10.+'
    testRuntimeOnly    'org.junit.vintage:junit-vintage-engine:5.10.+'
    testRuntimeOnly    'org.junit.platform:junit-platform-launcher:1.10.+'
    testImplementation 'org.apache.groovy:groovy:5.0.+'
    testImplementation 'org.spockframework:spock-core:2.4-groovy-5.0'

    testRuntimeOnly    'tomcat:naming-java:5.+'
    testRuntimeOnly    'tomcat:naming-factory:5.+'
    testRuntimeOnly    'tomcat:naming-resources:5.+'

    implementation     'com.github.masatokokubo:debugtrace:4.1.+'
    testImplementation 'com.github.masatokokubo:debugtrace:4.1.+'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

group = 'org.lightsleep'

def archivesName = 'lightsleep'

base {
    archivesName = "$archivesName"
}

version = '4.1.0-j17'

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
        }
    }
    test {
        java {
            srcDir 'src/test/java'
        }
        groovy {
            srcDir 'src/test/groovy'
        }
        resources {
            srcDir 'src/test/resources'
        }
    }
}

compileJava {
    options.encoding     = 'UTF-8'
    options.deprecation  = true
    options.debug        = true
    options.compilerArgs = ['-Xlint']
}

compileTestJava {
    options.encoding     = compileJava.options.encoding
    options.deprecation  = compileJava.options.deprecation
    options.debug        = compileJava.options.debug
    options.compilerArgs = compileJava.options.compilerArgs
}

processResources {
    duplicatesStrategy 'exclude'
}

processTestResources {
    duplicatesStrategy 'exclude'
}

jar {
    manifest {
        attributes  'Implementation-Title'    : project.name,
                    'Implementation-Version'  : version,
                    'Implementation-Vendor'   : 'Masato Kokubo',
                    'Implementation-Vendor-Id': 'dev.masatokokubo'
    }
}

test {
    useJUnitPlatform()
}

javadoc {
    title               = "$project.name $version API Specification"
    options.charSet     = 'UTF-8'
    options.encoding    = 'UTF-8'
    options.locale      = 'en'
    options.windowTitle = "$project.name"
    options.overview    = 'src/main/java/overview.html'
    options.addBooleanOption('author', true)
    options.addStringOption ('bottom', '<div class="copyright">&copy; 2016 Masato Kokubo</div>')
}

javadoc.doFirst {
    def cssFile = file('build/docs/javadoc/stylesheet.css')
    if (cssFile.exists())
        cssFile.delete()
}

javadoc.doLast {
    def cssFile = file('build/docs/javadoc/stylesheet.css')
    file('src/main/java/addtional.css').eachLine {
        cssFile.append("$it\n")
    }
}

task copyImages(type: Copy) {
    from 'images'
    into 'build/docs/images'
    include '**/*.gif'
}

build.dependsOn copyImages

task zip(type: Zip) {
    archiveClassifier = 'bin'
    preserveFileTimestamps = true
    into('/'      , {from "build/libs/${archivesName}-${version}.jar"})
    into('/'      , {from 'LICENSE.txt'})
    into('/'      , {from 'README.md', 'CHANGELOG.md', 'Tutorial.md', 'UserGuide.md'})
    into('/'      , {from 'README_ja.md', 'CHANGELOG_ja.md', 'Tutorial_ja.md', 'UserGuide_ja.md'})
    into('javadoc', {from 'build/docs/javadoc'})
}

tasks.withType(Jar).configureEach {
    preserveFileTimestamps = true
}

task sourcesJar(type: Jar) {
    archiveClassifier = 'sources'
    manifest {
        attributes  'Implementation-Title'    : project.name,
                    'Implementation-Version'  : version,
                    'Implementation-Vendor'   : 'Masato Kokubo',
                    'Implementation-Vendor-Id': 'dev.masatokokubo'
    }

    into('/org', {from 'src/main/java/org'})
}

task javadocJar(type: Jar, dependsOn:javadoc) {
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

java {
    withJavadocJar()
    withSourcesJar()
}
